# -*- coding: utf-8 -*-
"""Tsp-stress test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1op8S_CMj0sx37MBekQ7mWoRsTzog9B6p
"""

# tsp_beam_vs_hk_clean.py
# One-file runner:
# - Matrix generator: (n, seed, kind ∈ {asymmetric, symmetric, blocked})
# - Structural Beam TSP (bounded beam + tiny bounded 2-opt; polynomial)
# - Held–Karp exact TSP (directed + INF) for n <= 12
# - Independent route-cost recomputation guard for both solvers
# - Simple console output; matrix printed only on mismatch

import math, random, time, tracemalloc
from typing import List, Tuple, Optional

# -----------------------------
# Matrix generation
# -----------------------------
def generate_matrix(n: int, seed: int, kind: str = "asymmetric",
                    wmin: int = 1, wmax: int = 10, block_prob: float = 0.05) -> List[List[float]]:
    """
    kind:
      - "asymmetric": directed, random weights
      - "symmetric":  undirected (A[i][j] == A[j][i])
      - "blocked":    directed with some edges set to INF; ensures >=1 outgoing per node
    Diagonal is INF (no self-loops).
    """
    rng = random.Random(seed)
    INF = float('inf')
    A = [[INF]*n for _ in range(n)]

    if kind == "symmetric":
        for i in range(n):
            for j in range(i+1, n):
                w = rng.randint(wmin, wmax)
                A[i][j] = w
                A[j][i] = w
        # rare symmetric blockers
        for i in range(n):
            for j in range(i+1, n):
                if rng.random() < 0.02:
                    A[i][j] = INF
                    A[j][i] = INF

    elif kind == "blocked":
        for i in range(n):
            for j in range(n):
                if i == j:
                    continue
                if rng.random() < block_prob:
                    A[i][j] = INF
                else:
                    A[i][j] = rng.randint(wmin, wmax)
        # ensure at least one outgoing edge per node
        for i in range(n):
            if all(math.isinf(A[i][j]) for j in range(n)):
                j = rng.randrange(n)
                while j == i:
                    j = rng.randrange(n)
                A[i][j] = rng.randint(wmin, wmax)

    else:  # asymmetric
        for i in range(n):
            for j in range(n):
                if i == j:
                    continue
                A[i][j] = rng.randint(wmin, wmax)

    return A


# -----------------------------
# Structural Beam TSP + tiny bounded 2-opt repair (polynomial)
# -----------------------------
def tsp_structural_beam(matrix: List[List[float]], K=5, L=6, TAU=0.3, M=12
                       ) -> Tuple[Optional[List[int]], Optional[int]]:
    """
    Returns (closed_route_1based, cost_int) or (None, None).
    """
    import heapq
    n = len(matrix)
    INF = 10**12

    def blocked(i, j):   # diagonal or INF is blocked
        return i == j or matrix[i][j] == float('inf')

    # ---- tiny bounded 2-opt (keeps polynomial) ----
    def tour_cost0(tour0: List[int]) -> float:
        s = 0.0
        for a, b in zip(tour0, tour0[1:]):
            s += matrix[a][b]
        s += matrix[tour0[-1]][tour0[0]]
        return s

    def two_opt_once(tour0: List[int]):
        """Try first improving 2-opt; O(n^2). Returns (new_tour0, improved)."""
        nloc = len(tour0)
        for i in range(nloc - 1):
            a, b = tour0[i], tour0[(i+1) % nloc]
            for k in range(i+2, nloc - (0 if i > 0 else 1)):
                c, d = tour0[k], tour0[(k+1) % nloc]
                old = matrix[a][b] + matrix[c][d]
                new = matrix[a][c] + matrix[b][d]
                if new + 1e-12 < old:
                    if i+1 <= k:
                        new_tour = tour0[:i+1] + list(reversed(tour0[i+1:k+1])) + tour0[k+1:]
                    else:
                        seg = (tour0[i+1:] + tour0[:k+1])
                        seg.reverse()
                        new_tour = [*tour0[:i+1], *seg[:nloc-(i+1)], *seg[nloc-(i+1):], *tour0[k+1:]]
                    return new_tour, True
        return tour0, False

    def two_opt_repair(tour0: List[int], max_passes: int = 2) -> List[int]:
        cur = tour0[:]
        for _ in range(max_passes):
            cur, improved = two_opt_once(cur)
            if not improved:
                break
        return cur

    # ---- precompute neighbors ----
    out_neighbors = []
    for i in range(n):
        lst = [(j, matrix[i][j]) for j in range(n) if not blocked(i, j)]
        lst.sort(key=lambda x: x[1])
        out_neighbors.append(lst)

    rank_out = [[None]*n for _ in range(n)]
    best_out = [None]*n
    for i in range(n):
        for r, (j, w) in enumerate(out_neighbors[i]):
            rank_out[i][j] = r+1
        if out_neighbors[i]:
            best_out[i] = out_neighbors[i][0]

    incoming_anchor_sources = [[] for _ in range(n)]
    for i in range(n):
        if out_neighbors[i]:
            tgt = out_neighbors[i][0][0]
            incoming_anchor_sources[tgt].append(i)
    for j in range(n):
        incoming_anchor_sources[j].sort(key=lambda x: matrix[x][j])

    in_rank_best = [INF]*n
    for j in range(n):
        best = INF
        for i in range(n):
            if i != j and not blocked(i, j) and matrix[i][j] < best:
                best = matrix[i][j]
        in_rank_best[j] = best if best < INF else INF

    def cheap_lower_bound(unvisited: set, left: int, right: int):
        lb = 0.0
        for u in unvisited:
            best = INF
            for v, w in out_neighbors[u]:
                if v in unvisited or v == left or v == right:
                    if w < best: best = w
            lb += 0 if best == INF else best
        best_r = INF
        for v, w in out_neighbors[right]:
            if v in unvisited or v == left:
                if w < best_r: best_r = w
        lb += 0 if best_r == INF else best_r
        best_in = INF
        for src in incoming_anchor_sources[left]:
            if src in unvisited and matrix[src][left] < best_in:
                best_in = matrix[src][left]
        if best_in < INF:
            lb += best_in
        return lb

    def suspicion(u, v):
        s = 0
        if rank_out[u][v] and rank_out[u][v] <= 2: s += 1
        if best_out[u] and best_out[u][0] == v: s += 1
        if u in incoming_anchor_sources[v]: s += 1
        if matrix[u][v] <= in_rank_best[v]: s += 1
        return s

    def two_step_trap_right(right, used_set: set):
        feas = [(v, w) for (v, w) in out_neighbors[right] if v not in used_set]
        if len(feas) < 2: return False
        limit = min(len(feas), K+L)
        vals = []
        for idx in range(limit):
            v, w = feas[idx]
            best2 = 10**15
            for v2, w2 in out_neighbors[v]:
                if v2 not in used_set and v2 != right and w2 < best2:
                    best2 = w2
            vals.append(w + (0 if best2 >= 10**15 else best2))
        m = min(vals)
        return any(val <= 0.98*m for val in vals[1:])

    def two_step_trap_left(left, used_set: set):
        srcs = [x for x in incoming_anchor_sources[left] if x not in used_set]
        if len(srcs) < 2: return False
        limit = min(len(srcs), K+L)
        vals = []
        for idx in range(limit):
            u = srcs[idx]
            w = matrix[u][left]
            best2 = 10**15
            for v2, w2 in out_neighbors[u]:
                if v2 not in used_set and v2 != left and w2 < best2:
                    best2 = w2
            vals.append(w + (0 if best2 >= 10**15 else best2))
        m = min(vals)
        return any(val <= 0.98*m for val in vals[1:])

    anchors = []
    for i in range(n):
        if best_out[i] is not None:
            j, w = best_out[i]
            anchors.append((w, i, j))
    anchors.sort()

    best_overall = (INF, None)  # (cost_float, tour0)
    used_anchor_edge = set()

    def grow_from_seed(i0: int, j0: int):
        nonlocal best_overall, used_anchor_edge
        left, right = i0, j0
        used = frozenset({i0, j0})
        cur_cost = matrix[i0][j0]
        pL = (i0,)
        pR = (j0,)
        heap = []
        heapq.heappush(heap, (cur_cost, cur_cost, left, right, used, pL, pR))

        while heap:
            batch = []
            for _ in range(min(len(heap), M)):
                batch.append(heapq.heappop(heap))
            new_pool = []

            for heur, cur, left, right, used_f, pL, pR in batch:
                used_set = set(used_f)

                if len(used_set) == n and not blocked(right, left):
                    base_tour0 = list(pL[::-1]) + list(pR)
                    # bounded polynomial repair
                    repaired0 = two_opt_repair(base_tour0, max_passes=2)
                    # evaluate both exactly
                    base_cost = tour_cost0(base_tour0)
                    rep_cost  = tour_cost0(repaired0)
                    if rep_cost < base_cost:
                        total, final_tour0 = rep_cost, repaired0
                    else:
                        total, final_tour0 = base_cost, base_tour0
                    if total < best_overall[0]:
                        best_overall = (total, final_tour0)
                        for a, b in zip(final_tour0, final_tour0[1:] + [final_tour0[0]]):
                            if out_neighbors[a] and out_neighbors[a][0][0] == b:
                                used_anchor_edge.add((a, b))
                    continue

                # RIGHT candidates
                feasR = [(v, w) for (v, w) in out_neighbors[right] if v not in used_set]
                r_mand = feasR[:K]
                r_extra = feasR[K:K+L] if len(feasR) > K else []
                openR = False
                if len(feasR) >= 2:
                    w1 = feasR[0][1]; w2 = feasR[1][1]
                    if w1 > 0 and (w2 - w1)/w1 <= TAU: openR = True
                unvisited = [u for u in range(n) if u not in used_set]
                if best_overall[0] < INF:
                    lb = cheap_lower_bound(set(unvisited), left, right)
                    if cur + lb >= 0.95*best_overall[0]: openR = True
                for (v, w) in r_extra:
                    if suspicion(right, v) >= 2: openR = True; break
                if two_step_trap_right(right, used_set): openR = True
                r_cands = r_mand + (r_extra if openR else [])

                # LEFT candidates
                sources = [x for x in incoming_anchor_sources[left] if x not in used_set]
                l_mand = [(x, matrix[x][left]) for x in sources[:K]]
                l_extra = [(x, matrix[x][left]) for x in sources[K:K+L]] if len(sources) > K else []
                openL = False
                if len(sources) >= 2:
                    w1 = matrix[sources[0]][left]; w2 = matrix[sources[1]][left]
                    if w1 > 0 and (w2 - w1)/w1 <= TAU: openL = True
                if best_overall[0] < INF:
                    lb = cheap_lower_bound(set(unvisited), left, right)
                    if cur + lb >= 0.95*best_overall[0]: openL = True
                for (x, w) in l_extra:
                    if suspicion(x, left) >= 2: openL = True; break
                if two_step_trap_left(left, used_set): openL = True
                l_cands = l_mand + (l_extra if openL else [])

                # bounded escape if both sides empty
                if not r_cands and not l_cands:
                    extra_r = None
                    for v, w in out_neighbors[right]:
                        if v not in used_set: extra_r = (v, w); break
                    extra_l = None
                    best_w_in, best_u = INF, None
                    for u in range(n):
                        if u not in used_set and not blocked(u, left):
                            if matrix[u][left] < best_w_in:
                                best_w_in, best_u = matrix[u][left], u
                    if best_u is not None: extra_l = (best_u, best_w_in)
                    if extra_r is None and extra_l is None: continue
                    if extra_r is not None: r_cands = [extra_r]
                    if extra_l is not None: l_cands = [extra_l]

                # expand right
                for (v, w) in r_cands:
                    new_used = set(used_set); new_used.add(v)
                    new_pL = pL; new_pR = pR + (v,)
                    new_left = left; new_right = v
                    new_cur = cur + w
                    unvis2 = [u for u in range(n) if u not in new_used]
                    lb = cheap_lower_bound(set(unvis2), new_left, new_right)
                    heur2 = new_cur + lb
                    heapq.heappush(new_pool, (heur2, new_cur, new_left, new_right, frozenset(new_used), new_pL, new_pR))

                # expand left
                for (x, w) in l_cands:
                    new_used = set(used_set); new_used.add(x)
                    new_pL = pL + (x,)
                    new_pR = pR
                    new_left = x; new_right = right
                    new_cur = cur + w
                    unvis2 = [u for u in range(n) if u not in new_used]
                    lb = cheap_lower_bound(set(unvis2), new_left, new_right)
                    heur2 = new_cur + lb
                    heapq.heappush(new_pool, (heur2, new_cur, new_left, new_right, frozenset(new_used), new_pL, new_pR))

            if not new_pool:
                heap = []
                break
            new_pool.sort(key=lambda x: x[0])
            heap = new_pool[:M]

    for _, i, j in anchors:
        if blocked(i, j):
            continue
        grow_from_seed(i, j)

    if best_overall[1] is None:
        return None, None

    # Build 1-based CLOSED route and recompute cost independently
    route0 = best_overall[1]
    route_1b = [x+1 for x in route0]
    if route_1b[0] != route_1b[-1]:
        route_1b = route_1b + [route_1b[0]]
    cost_exact = recompute_cost_1based(matrix, route_1b)
    return route_1b, (None if cost_exact is None else int(cost_exact))


# -----------------------------
# Independent route-cost recomputation (guard)
# -----------------------------
def recompute_cost_1based(matrix: List[List[float]], route_1b_closed: List[int]) -> Optional[float]:
    """Sum cost of a closed 1-based route; returns None if any edge is INF or invalid."""
    if not route_1b_closed or route_1b_closed[0] != route_1b_closed[-1]:
        return None
    total = 0.0
    for a1, b1 in zip(route_1b_closed, route_1b_closed[1:]):
        a = a1 - 1; b = b1 - 1
        w = matrix[a][b]
        if math.isinf(w):
            return None
        total += w
    return total


# -----------------------------
# Held–Karp exact TSP (directed + INF) for n <= 12
# -----------------------------
def held_karp_tsp(matrix: List[List[float]]) -> Tuple[Optional[List[int]], Optional[int]]:
    """
    Returns (closed_route_1based, opt_cost_int) or (None, None) if no Hamiltonian cycle exists.
    Start node is 0, and we return to 0.
    Complexity: O(n^2 2^n). Only use for n <= 12.
    """
    n = len(matrix)
    INF = float('inf')

    # dp[(mask, j)] = (cost, prev)
    dp = {}
    for j in range(1, n):
        if not math.isinf(matrix[0][j]):
            dp[(1 << 0) | (1 << j), j] = (matrix[0][j], 0)

    # build DP by subset size
    for size in range(3, n+1):
        for mask in range(1 << n):
            if mask & 1 == 0:      # must include start
                continue
            if mask.bit_count() != size:
                continue
            # transitions to j (end)
            for j in range(1, n):
                key = (mask, j)
                if (mask & (1 << j)) == 0:
                    continue
                best = None
                prev_best = None
                pmask = mask ^ (1 << j)
                # predecessor i
                for i in range(n):
                    if i == j or (pmask & (1 << i)) == 0:
                        continue
                    if (pmask, i) not in dp:
                        continue
                    if math.isinf(matrix[i][j]):
                        continue
                    cand = dp[(pmask, i)][0] + matrix[i][j]
                    if best is None or cand < best:
                        best = cand
                        prev_best = i
                if best is not None:
                    dp[key] = (best, prev_best)

    full = (1 << n) - 1
    best_cost = None
    best_end = None
    for j in range(1, n):
        key = (full, j)
        if key not in dp:
            continue
        if math.isinf(matrix[j][0]):
            continue
        cand = dp[key][0] + matrix[j][0]
        if best_cost is None or cand < best_cost:
            best_cost = cand
            best_end = j

    if best_cost is None:
        return None, None

    # reconstruct route 0 -> ... -> 0
    route = [0]
    j = best_end
    mask = full
    path_rev = [j]
    while j != 0:
        cost_j, prev_j = dp[(mask, j)]
        mask ^= (1 << j)
        j = prev_j
        if j != 0:
            path_rev.append(j)
    path_rev.reverse()
    route.extend(path_rev)
    route.append(0)
    route_1b = [x+1 for x in route]

    # independent guard (should equal best_cost)
    chk = recompute_cost_1based(matrix, route_1b)
    if chk is None:
        # should not happen; treat as failure
        return None, None
    return route_1b, int(chk)


# -----------------------------
# Experiment runner
# -----------------------------
def run_case(n: int, seed: int, kind: str, K=5, L=6, TAU=0.3, M=12, hk_limit: int = 12):
    print(f"\n=== n={n}, seed={seed}, kind={kind} ===")
    mat = generate_matrix(n, seed, kind)

    # Beam timing/memory ONLY
    tracemalloc.start()
    t0 = time.perf_counter()
    b_route, b_cost = tsp_structural_beam(mat, K=K, L=L, TAU=TAU, M=M)
    t1 = time.perf_counter()
    cur, peak = tracemalloc.get_traced_memory()
    tracemalloc.stop()
    beam_time = t1 - t0
    beam_mem_mb = peak / (1024*1024)

    if b_route is None:
        print("Beam: No complete tour found.")
    else:
        # recompute cost independently (guard)
        b_cost_chk = recompute_cost_1based(mat, b_route)
        print(f"Beam cost : {b_cost if b_cost is not None else 'None'}  | recomputed: {int(b_cost_chk) if b_cost_chk is not None else 'None'}")
        print("Beam route:", " -> ".join(map(str, b_route)))
    print(f"Beam time : {beam_time:.6f}s | Peak mem: {beam_mem_mb:.3f} MB")

    # HK verification (n <= hk_limit)
    if n <= hk_limit:
        hk_route, hk_cost = held_karp_tsp(mat)
        if hk_route is None:
            print("HK: No Hamiltonian cycle exists (given blocks).")
            verified = (b_route is None)
        else:
            hk_cost_chk = recompute_cost_1based(mat, hk_route)
            print(f"HK cost  : {hk_cost}  | recomputed: {int(hk_cost_chk) if hk_cost_chk is not None else 'None'}")
            print("HK route :", " -> ".join(map(str, hk_route)))
            # Compare recomputed costs to avoid any printing/rounding mishaps
            if b_route is not None and b_cost is not None and hk_cost_chk is not None:
                verified = (int(b_cost_chk) == int(hk_cost_chk))
            else:
                verified = (b_route is None and hk_route is None)

        if verified:
            print("✅ MATCH — beam equals HK (using recomputed costs).")
        else:
            print("❌ MISMATCH — investigate. Matrix follows:")
            for row in mat:
                print("  ", ["INF" if math.isinf(x) else int(x) for x in row])
    else:
        print(f"(HK skipped for n={n}; limit={hk_limit})")


# -----------------------------
# Main: edit CASES as you like
# -----------------------------
if __name__ == "__main__":
    # A small suite you can change quickly
    CASES = [
        (90, 1, "symmetric"),
        (100, 1, "asymmetric"),
        (100, 1, "blocked"),
        (100, 1, "symmetric"),
    ]
    for n, seed, kind in CASES:
        run_case(n, seed, kind, K=6, L=10, TAU=0.35, M=24, hk_limit=14)